import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import { Analytics } from '@vercel/analytics/react'

const ayerPoster = localFont({ src: '../../public/fonts/AyerPoster-Medium.woff2' })

export const metadata: Metadata = {
  title: 'Atlas of broken solids',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={ayerPoster.className}>
        {children}
      </body>
      <Analytics />
    </html>
  )
}
